export const ENTITY_KINDS = {
    UNIT: 'unit',
    BUILDING: 'building',
}

export const MOVEMENT_TYPES = {
    GROUND: 'ground',
    NAVAL: 'naval',
    AIR: 'air',
}

export const UNIT_TYPES = {
    MECH: {
        sprite: 'mech',
        name: 'Mech',
        movement: MOVEMENT_TYPES.GROUND,
        radius: 18,
        speed: 120,
        sightRange: 260,
        maxHealth: 120,
        damage: 12,
        attacksPerSecond: 1.6,
        attackRange: 120,
        cost: 50,
        populationCost: 1,
        spawnCooldownSeconds: 4,
        cruiseAltitude: 0,
        miningCapacity: 0,
        miningRate: 0,
    },
    GLIDER: {
        sprite: 'glider',
        name: 'Glider',
        movement: MOVEMENT_TYPES.AIR,
        radius: 16,
        speed: 220,
        sightRange: 360,
        maxHealth: 60,
        damage: 6,
        attacksPerSecond: 3,
        attackRange: 100,
        cost: 40,
        populationCost: 1,
        spawnCooldownSeconds: 3,
        cruiseAltitude: 32,
        miningCapacity: 20,
        miningRate: 6,
    },
    BOAT: {
        sprite: 'boat',
        name: 'Boat',
        movement: MOVEMENT_TYPES.NAVAL,
        radius: 24,
        speed: 150,
        sightRange: 300,
        maxHealth: 160,
        damage: 18,
        attacksPerSecond: 1.1,
        attackRange: 160,
        cost: 80,
        populationCost: 2,
        spawnCooldownSeconds: 6,
        cruiseAltitude: 0,
        miningCapacity: 0,
        miningRate: 0,
    },
}

export const BUILDING_TYPES = {
    CORE: {
        sprite: 'core',
        name: 'Core',
        size: 4,
        height: 56,
        sightRange: 420,
        maxHealth: 3000,
        cost: 0,
        acceptsOre: true,
        oreIncomePerSecond: 2,
        buildSeconds: 0,
        populationSupply: 10,
        spawns: ['MECH'],
        requiresWater: false,
    },
    FACTORY: {
        sprite: 'factory',
        name: 'Factory',
        size: 3,
        height: 40,
        sightRange: 260,
        maxHealth: 1200,
        cost: 120,
        acceptsOre: false,
        buildSeconds: 12,
        populationSupply: 0,
        spawns: ['MECH'],
        requiresWater: false,
    },
    AIRFIELD: {
        sprite: 'airfield',
        name: 'Airfield',
        size: 3,
        height: 36,
        sightRange: 300,
        maxHealth: 900,
        cost: 120,
        acceptsOre: true,
        buildSeconds: 12,
        populationSupply: 0,
        spawns: ['GLIDER'],
        requiresWater: false,
    },
    SHIPYARD: {
        sprite: 'shipyard',
        name: 'Shipyard',
        size: 2,
        height: 32,
        sightRange: 260,
        maxHealth: 800,
        cost: 100,
        acceptsOre: false,
        buildSeconds: 10,
        populationSupply: 0,
        spawns: ['BOAT'],
        requiresWater: true,
    },
    HABITAT: {
        sprite: 'habitat',
        name: 'Habitat',
        size: 2,
        height: 30,
        sightRange: 220,
        maxHealth: 700,
        cost: 60,
        acceptsOre: false,
        buildSeconds: 8,
        populationSupply: 6,
        spawns: [],
        requiresWater: false,
    },
    TURRET: {
        sprite: 'turret',
        name: 'Turret',
        size: 1,
        height: 30,
        sightRange: 300,
        maxHealth: 500,
        cost: 80,
        acceptsOre: false,
        buildSeconds: 8,
        populationSupply: 0,
        spawns: [],
        requiresWater: false,
        damage: 10,
        attacksPerSecond: 2,
        attackRange: 240,
    },
    WALL: {
        sprite: 'wall',
        name: 'Wall',
        size: 1,
        height: 28,
        sightRange: 140,
        maxHealth: 600,
        cost: 10,
        acceptsOre: false,
        buildSeconds: 3,
        populationSupply: 0,
        spawns: [],
        requiresWater: false,
    },
}

export const CONSTRUCTIBLE_BUILDING_KEYS = ['HABITAT', 'FACTORY', 'AIRFIELD', 'SHIPYARD', 'TURRET', 'WALL']
